version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true 
    ports: 
      - "3000:3000" #3000 map to 3000
    networks: 
      - mern-app #enable to communicate each other 
    volumes: 
      - ./frontend/:/usr/src/app 
      - /usr/src/app/node_modules 
  api-server:
    image: api-server 
    build: ./backend/
    ports :
      - "3001:3001"
    networks: 
      - mern-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules

networks:
  mern-app:
    driver: bridge #default driver 
  